#!/usr/bin/env bash
# Instructions for obtaining real NASDAQ ITCH 5.0 historical data.
#
# Two free sources:
#   1. NASDAQ Historical Data (requires free registration)
#   2. lobsterdata.com (Level 2 order book data, academic use)
#
# This script does NOT download automatically — it prints the steps.
# After downloading, run the replay binary against the file.

set -euo pipefail

echo "=== NASDAQ ITCH 5.0 Historical Data ==="
echo ""
echo "━━━ Option 1: NASDAQ BinaryFTP (free, requires registration) ━━━"
echo ""
echo "  1. Register at: https://www.nasdaqtrader.com/Trader.aspx?id=HistoricalData"
echo "     (free account, takes ~1 business day to approve)"
echo ""
echo "  2. After approval, files are available via FTP:"
echo "     Host:  ftp.nasdaqtrader.com"
echo "     Dir:   /itch/"
echo "     Files: S<MMDDYY>-v50.gz  (e.g. S081322-v50.gz = Aug 13, 2022)"
echo ""
echo "  3. Download and decompress:"
echo "     ftp ftp.nasdaqtrader.com"
echo "     # login: anonymous, password: your@email.com"
echo "     get /itch/S081322-v50.gz"
echo "     exit"
echo "     gunzip S081322-v50.gz"
echo "     # Result: S081322-v50  (~5-12 GB per day)"
echo ""
echo "  4. Replay:"
echo "     ./build/replay S081322-v50 AAPL"
echo "     ./build/replay S081322-v50 MSFT"
echo ""
echo "━━━ Option 2: lobsterdata.com (pre-processed Level 2, academic) ━━━"
echo ""
echo "  1. Visit: https://lobsterdata.com/"
echo "     Apply for academic access (free for researchers/students)"
echo ""
echo "  2. Data comes as CSV (not raw ITCH). Use their Python tools"
echo "     to convert back to ITCH format, or adapt our replay engine"
echo "     to read LOBSTER CSV directly."
echo ""
echo "━━━ Option 3: Generate synthetic data (no registration needed) ━━━"
echo ""
echo "  python3 scripts/generate_sample_itch.py \\"
echo "      --out data/sample.itch \\"
echo "      --messages 1000000 \\"
echo "      --symbols AAPL MSFT TSLA"
echo ""
echo "  ./build/replay data/sample.itch AAPL"
echo ""
echo "━━━ Expected file sizes (real NASDAQ data) ━━━"
echo ""
echo "  Full trading day:  5–12 GB (compressed: 1–3 GB)"
echo "  Messages per day:  ~400–600 million"
echo "  AAPL messages:     ~10–20 million per day"
echo ""
echo "━━━ Quick integrity check after download ━━━"
echo ""
echo "  # Verify it looks like ITCH (first byte of first message = 'S' = 0x53)"
echo "  od -A x -t x1z -v <your_file.itch | head -5"
echo "  # First non-header byte should be one of: R S A F E X D U P Q B"
echo ""
echo "━━━ Replay with real data ━━━"
echo ""
echo "  # Basic replay (prints stats, no verbose trade output):"
echo "  ./build/replay /path/to/S081322-v50 AAPL"
echo ""
echo "  # Benchmark throughput with real data:"
echo "  # (modify replay_bench.cpp to use MmapReader instead of synthetic data)"
echo ""
